# Configuration preprocessor
constants:
  WORK_DIR: $$$WORK_DIR$$$/$$$TARGET_NAME$$$
---

general:
  logger:
    log-level: warning
    file: $$WORK_DIR$$/work/log.txt
  monitor:
    enable: true
    sample-rate: 50
    
testcase:
  module: load
  module-options:
    input-directory: $$$JS_TESTCASE_DIRECTORY$$$
    
trace:
  module: passthrough
  options:
    input-buffer-size: 4
    
preprocess:
  module: load
  module-options:
    input-directory: $$WORK_DIR$$/work/traces
  options:
    input-buffer-size: 4
    max-parallel-threads: 4
  
analysis:
  modules:
    - module: control-flow-leakage
      module-options:
        output-directory: $$WORK_DIR$$/persist/results
        map-directory: $$WORK_DIR$$/work/maps
        dump-call-tree: false
        include-testcases-in-call-stacks: false
        
  options:
    input-buffer-size: 3
    max-parallel-threads: 1
