# Configuration preprocessor
constants:
  WORK_DIR: $$$WORK_DIR$$$/$$$TARGET_NAME$$$
---

general:
  logger:
    log-level: warning
    file: $$WORK_DIR$$/work/log.txt
  monitor:
    enable: true
    sample-rate: 50
    
testcase:
  module: load
  module-options:
    input-directory: $$$JS_TESTCASE_DIRECTORY$$$
    
trace:
  module: load
  module-options:
    input-directory: $$WORK_DIR$$/work/traces
  options:
    input-buffer-size: 5
    
preprocess:
  module: js
  module-options:
    output-directory: $$WORK_DIR$$/work/traces
    map-directory: $$WORK_DIR$$/work/maps
    store-traces: true
  options:
    input-buffer-size: 4
    max-parallel-threads: 4
  
analysis:
  modules:
    - module: passthrough
  options:
    input-buffer-size: 4
    max-parallel-threads: 1
